/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csc4380.pphejlada1.project1;


import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Random;


/**
 *
 * @author Sarina & Nikhita
 */
public class Hangman extends javax.swing.JFrame {
    public String word; //secret word to be guessed
    public String[] words = {"computers", "program", "internet","source","science"}; //list of secret words
    char[] guessWord; //char array to hold correct guesses so far
    char[] guessed; //char array of secret word
    public static int wrong; //number of wrong guesses
    Man man;
    /**
     * Creates new form Hangman
     */
    public Hangman() {
        initComponents();
        CenterMe();     
        initGraphics();
    }
    public void CenterMe(){
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((screen.getWidth() - getWidth()) /2);
        int y = (int) ((screen.getHeight() -getHeight()) /2);
        setLocation(x, y); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        letA = new javax.swing.JButton();
        letB = new javax.swing.JButton();
        letC = new javax.swing.JButton();
        letD = new javax.swing.JButton();
        letE = new javax.swing.JButton();
        letF = new javax.swing.JButton();
        letG = new javax.swing.JButton();
        letH = new javax.swing.JButton();
        letI = new javax.swing.JButton();
        letJ = new javax.swing.JButton();
        letK = new javax.swing.JButton();
        letL = new javax.swing.JButton();
        letM = new javax.swing.JButton();
        letN = new javax.swing.JButton();
        letO = new javax.swing.JButton();
        letP = new javax.swing.JButton();
        letQ = new javax.swing.JButton();
        letR = new javax.swing.JButton();
        letS = new javax.swing.JButton();
        letT = new javax.swing.JButton();
        letU = new javax.swing.JButton();
        letV = new javax.swing.JButton();
        letW = new javax.swing.JButton();
        letX = new javax.swing.JButton();
        letY = new javax.swing.JButton();
        letZ = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnGiveUp = new javax.swing.JButton();
        btnNewWord = new javax.swing.JButton();
        txtWord = new javax.swing.JLabel();
        txtGameOver = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mnuClose = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hangman The Game!");

        letA.setText("A");
        letA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letAActionPerformed(evt);
            }
        });

        letB.setText("B");
        letB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letBActionPerformed(evt);
            }
        });

        letC.setText("C");
        letC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letCActionPerformed(evt);
            }
        });

        letD.setText("D");
        letD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letDActionPerformed(evt);
            }
        });

        letE.setText("E");
        letE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letEActionPerformed(evt);
            }
        });

        letF.setText("F");
        letF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letFActionPerformed(evt);
            }
        });

        letG.setText("G");
        letG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letGActionPerformed(evt);
            }
        });

        letH.setText("H");
        letH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letHActionPerformed(evt);
            }
        });

        letI.setText("I");
        letI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letIActionPerformed(evt);
            }
        });

        letJ.setText("J");
        letJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letJActionPerformed(evt);
            }
        });

        letK.setText("K");
        letK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letKActionPerformed(evt);
            }
        });

        letL.setText("L");
        letL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letLActionPerformed(evt);
            }
        });

        letM.setText("M");
        letM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letMActionPerformed(evt);
            }
        });

        letN.setText("N");
        letN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letNActionPerformed(evt);
            }
        });

        letO.setText("O");
        letO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letOActionPerformed(evt);
            }
        });

        letP.setText("P");
        letP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letPActionPerformed(evt);
            }
        });

        letQ.setText("Q");
        letQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letQActionPerformed(evt);
            }
        });

        letR.setText("R");
        letR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letRActionPerformed(evt);
            }
        });

        letS.setText("S");
        letS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letSActionPerformed(evt);
            }
        });

        letT.setText("T");
        letT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letTActionPerformed(evt);
            }
        });

        letU.setText("U");
        letU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letUActionPerformed(evt);
            }
        });

        letV.setText("V");
        letV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letVActionPerformed(evt);
            }
        });

        letW.setText("W");
        letW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letWActionPerformed(evt);
            }
        });

        letX.setText("X");
        letX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letXActionPerformed(evt);
            }
        });

        letY.setText("Y");
        letY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letYActionPerformed(evt);
            }
        });

        letZ.setText("Z");
        letZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letZActionPerformed(evt);
            }
        });

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnGiveUp.setText("Give Up");
        btnGiveUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiveUpActionPerformed(evt);
            }
        });

        btnNewWord.setText("New Word");
        btnNewWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewWordActionPerformed(evt);
            }
        });

        txtWord.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        txtWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtGameOver.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        txtGameOver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtGameOver.setText("Press Start!");

        jMenu2.setText("File");

        mnuClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mnuClose.setText("Close");
        mnuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCloseActionPerformed(evt);
            }
        });
        jMenu2.add(mnuClose);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(txtGameOver, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(letJ)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letK)
                                    .addGap(10, 10, 10)
                                    .addComponent(letL)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letM)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(letN))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(letA)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letC)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letD)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(letO)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letP)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letQ)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(letR))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(letF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letG)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(letH)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(letI))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(letS)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letT)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letU)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letV)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letW)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letX)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letY)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(letZ))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStart)
                        .addGap(34, 34, 34)
                        .addComponent(btnGiveUp)
                        .addGap(33, 33, 33)
                        .addComponent(btnNewWord)
                        .addGap(94, 94, 94)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtGameOver, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnGiveUp)
                    .addComponent(btnNewWord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letA)
                    .addComponent(letB)
                    .addComponent(letC)
                    .addComponent(letD)
                    .addComponent(letE)
                    .addComponent(letF)
                    .addComponent(letG)
                    .addComponent(letH)
                    .addComponent(letI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letJ)
                    .addComponent(letK)
                    .addComponent(letL)
                    .addComponent(letM)
                    .addComponent(letN)
                    .addComponent(letO)
                    .addComponent(letP)
                    .addComponent(letQ)
                    .addComponent(letR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letS)
                    .addComponent(letT)
                    .addComponent(letU)
                    .addComponent(letV)
                    .addComponent(letW)
                    .addComponent(letX)
                    .addComponent(letY)
                    .addComponent(letZ))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void initGraphics(){
        man = new Man();
        this.add(man);
        man.setSize(600,600);
    }
    public String createWord(){ //selects the secret word
        int rand = new Random().nextInt(words.length);
        word = words[rand];
        guessed = word.toCharArray();
        return word;
    }
    public void createSpaces(){ //creates the number of lines for each char in secret word
        guessWord = new char[word.length()];
        for(int x = 0; x < word.length(); x++){
            guessWord[x] = '+';
        } 
    }
    public void updateSpaces(){ //prints out the secret word with guesses
        String wordGuessed = new String(guessWord);
        txtWord.setText(wordGuessed);
    }
    public void checkGuess(char guess){ //checks if guess is correct
        boolean included = false;
        for(int x = 0; x < guessWord.length; x++){
            if(word.charAt(x) == guess){
                guessWord[x] = guessed[x];
                included= true;
            }
        }
        if (!(new String(guessWord).contains("+"))) //checks if winner
            txtGameOver.setText("Winner!");
        if(included == false){
            wrong++;
            repaint();
            if(wrong==6){ //checks if game over
                txtGameOver.setText("GAME OVER");
                for(int x = 0; x < guessWord.length; x++){
                    guessWord[x] = guessed[x];
                }
            }     
        } 
    }
    //All letter keys are available to view again
    public void resetLetters(){
        letA.setVisible(true);
        letB.setVisible(true);
        letC.setVisible(true);
        letD.setVisible(true);
        letE.setVisible(true);
        letF.setVisible(true);
        letG.setVisible(true);
        letH.setVisible(true);
        letI.setVisible(true);
        letJ.setVisible(true);
        letK.setVisible(true);
        letL.setVisible(true);
        letM.setVisible(true);
        letN.setVisible(true);
        letO.setVisible(true);
        letP.setVisible(true);
        letQ.setVisible(true);
        letR.setVisible(true);
        letS.setVisible(true);
        letT.setVisible(true);
        letU.setVisible(true);
        letV.setVisible(true);
        letW.setVisible(true);
        letX.setVisible(true);
        letY.setVisible(true);
        letZ.setVisible(true);
    }
    private void letAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letAActionPerformed
        checkGuess('a');
        updateSpaces();
        letA.setVisible(false);
    }//GEN-LAST:event_letAActionPerformed

    private void letBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letBActionPerformed
        checkGuess('b');
        updateSpaces();
        letB.setVisible(false);
    }//GEN-LAST:event_letBActionPerformed

    private void letCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letCActionPerformed
        checkGuess('c');
        updateSpaces();
        letC.setVisible(false);
    }//GEN-LAST:event_letCActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        txtGameOver.setText(null);
        createWord();
        createSpaces();
        updateSpaces();
        resetLetters();
        txtGameOver.setText("");
        wrong = 0;
        repaint();
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnNewWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewWordActionPerformed
        txtGameOver.setText(null);
        createWord();
        createSpaces();
        updateSpaces();
        resetLetters();
        wrong = 0;
        repaint();
    }//GEN-LAST:event_btnNewWordActionPerformed

    private void btnGiveUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiveUpActionPerformed
        txtWord.setText(word);
        wrong = 0;
        txtGameOver.setText(null);
        txtGameOver.setText("Loser!");
    }//GEN-LAST:event_btnGiveUpActionPerformed

    private void letDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letDActionPerformed
        checkGuess('d');
        updateSpaces();
        letD.setVisible(false);
    }//GEN-LAST:event_letDActionPerformed

    private void letEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letEActionPerformed
        checkGuess('e');
        updateSpaces();
        letE.setVisible(false);
    }//GEN-LAST:event_letEActionPerformed

    private void letFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letFActionPerformed
        checkGuess('f');
        updateSpaces();
        letF.setVisible(false);
    }//GEN-LAST:event_letFActionPerformed

    private void letGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letGActionPerformed
        checkGuess('g');
        updateSpaces();
        letG.setVisible(false);
    }//GEN-LAST:event_letGActionPerformed

    private void letHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letHActionPerformed
        checkGuess('h');
        updateSpaces();
        letH.setVisible(false);
    }//GEN-LAST:event_letHActionPerformed

    private void letIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letIActionPerformed
        checkGuess('i');
        updateSpaces();
        letI.setVisible(false);
    }//GEN-LAST:event_letIActionPerformed

    private void letJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letJActionPerformed
        checkGuess('j');
        updateSpaces();
        letJ.setVisible(false);
    }//GEN-LAST:event_letJActionPerformed

    private void letKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letKActionPerformed
        checkGuess('k');
        updateSpaces();
        letK.setVisible(false);
    }//GEN-LAST:event_letKActionPerformed

    private void letLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letLActionPerformed
        checkGuess('l');
        updateSpaces();
        letL.setVisible(false);
    }//GEN-LAST:event_letLActionPerformed

    private void letMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letMActionPerformed
        checkGuess('m');
        updateSpaces();
        letM.setVisible(false);
    }//GEN-LAST:event_letMActionPerformed

    private void letNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letNActionPerformed
        checkGuess('n');
        updateSpaces();
        letN.setVisible(false);
    }//GEN-LAST:event_letNActionPerformed

    private void letOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letOActionPerformed
        checkGuess('o');
        updateSpaces();
        letO.setVisible(false);
    }//GEN-LAST:event_letOActionPerformed

    private void letPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letPActionPerformed
        checkGuess('p');
        updateSpaces();
        letP.setVisible(false);
    }//GEN-LAST:event_letPActionPerformed

    private void letQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letQActionPerformed
        checkGuess('q');
        updateSpaces();
        letQ.setVisible(false);
    }//GEN-LAST:event_letQActionPerformed

    private void letRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letRActionPerformed
        checkGuess('r');
        updateSpaces();
        letR.setVisible(false);
    }//GEN-LAST:event_letRActionPerformed

    private void letSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letSActionPerformed
        checkGuess('s');
        updateSpaces();
        letS.setVisible(false);
    }//GEN-LAST:event_letSActionPerformed

    private void letTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letTActionPerformed
        checkGuess('t');
        updateSpaces();
        letT.setVisible(false);
    }//GEN-LAST:event_letTActionPerformed

    private void letUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letUActionPerformed
        checkGuess('u');
        updateSpaces();
        letU.setVisible(false);
    }//GEN-LAST:event_letUActionPerformed

    private void letVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letVActionPerformed
        checkGuess('v');
        updateSpaces();
        letV.setVisible(false);
    }//GEN-LAST:event_letVActionPerformed

    private void letWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letWActionPerformed
        checkGuess('w');
        updateSpaces();
        letW.setVisible(false);
    }//GEN-LAST:event_letWActionPerformed

    private void letXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letXActionPerformed
        checkGuess('x');
        updateSpaces();
        letX.setVisible(false);
    }//GEN-LAST:event_letXActionPerformed

    private void letYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letYActionPerformed
        checkGuess('y');
        updateSpaces();
        letY.setVisible(false);
    }//GEN-LAST:event_letYActionPerformed

    private void letZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letZActionPerformed
        checkGuess('z');
        updateSpaces();
        letZ.setVisible(false);
    }//GEN-LAST:event_letZActionPerformed

    private void mnuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCloseActionPerformed
        // TODO add your handling code here:
                System.exit(0);
    }//GEN-LAST:event_mnuCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
                new Hangman().setVisible(true);           
            }
            
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiveUp;
    private javax.swing.JButton btnNewWord;
    private javax.swing.JButton btnStart;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton letA;
    private javax.swing.JButton letB;
    private javax.swing.JButton letC;
    private javax.swing.JButton letD;
    private javax.swing.JButton letE;
    private javax.swing.JButton letF;
    private javax.swing.JButton letG;
    private javax.swing.JButton letH;
    private javax.swing.JButton letI;
    private javax.swing.JButton letJ;
    private javax.swing.JButton letK;
    private javax.swing.JButton letL;
    private javax.swing.JButton letM;
    private javax.swing.JButton letN;
    private javax.swing.JButton letO;
    private javax.swing.JButton letP;
    private javax.swing.JButton letQ;
    private javax.swing.JButton letR;
    private javax.swing.JButton letS;
    private javax.swing.JButton letT;
    private javax.swing.JButton letU;
    private javax.swing.JButton letV;
    private javax.swing.JButton letW;
    private javax.swing.JButton letX;
    private javax.swing.JButton letY;
    private javax.swing.JButton letZ;
    private javax.swing.JMenuItem mnuClose;
    private javax.swing.JLabel txtGameOver;
    private javax.swing.JLabel txtWord;
    // End of variables declaration//GEN-END:variables
}

